name: CI Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt
          python -m pip install -r dev-requirements.txt

      - name: Run unit tests
        run: python -m coverage run -m pytest -v

      - name: Report coverage
        run: python -m coverage report --show-missing

      - name: Build package
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist
          retention-days: 1


  staging:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build files artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: dist

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel twine

      - name: Deploy package to TestPyPi
        env:
          USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: python -m twine upload --repository testpypi dist/* -u $USERNAME -p $PASSWORD